<?php

namespace ApiCore\Filament;

use ApiCore\Http\Resources\BaseResource;
use Filament\Clusters\Cluster;
use Filament\Resources\Resource;
use Filament\Tables\Table;
use Illuminate\Support\Str;

class BaseFilamentResource extends Resource
{

    public static function modelSlug(): string
    {
        return Str::slug(class_basename(static::$model));
    }

    public static function getNavigationGroup(): ?string
    {
        return trans('general.navigation.' . static::modelSlug()); // TODO: Change the autogenerated stub
    }

    public static function getPluralLabel(): ?string
    {
        return trans(static::modelSlug() . '.title');
    }


    public static function getNavigationLabel(): string
    {
        return trans(static::modelSlug() . '.title'); // TODO: Change the autogenerated stub
    }

    public static function getLabel(): ?string
    {
        return trans(static::modelSlug() . '.single'); // TODO: Change the autogenerated stub
    }
}
